### ISSUE TITLE
New version of Auth0 Deploy CLI Released

### ISSUE THREAD

**Issue by NotMyself** [auth0-training/labs-vscode-extension#49]
Version [v7.17.2](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.17.2) of the deploy cli has been released and should be updated to support new features and management api checks.

**Comment by kazemicode** [comment]
Newest is now [https://github.com/auth0/auth0-deploy-cli/releases/tag/v.7.17.3](v7.17.3)!

**Comment by NotMyself** [comment]
They released a new version that quick!?! Must be changes in the Management API.
