### ISSUE TITLE
CodeTour extension installed locally in VSCode

### ISSUE THREAD

**Issue by NotMyself** [auth0-training/labs-vscode-extension#8]
@jesposito identified an issue where having the CodeTour extension installed locally in VSCode can cause the container initialization process to throw an error.

Repo Steps:
1. Install VSCode and the Remote Development and CodTour extensions.
2. Start Docker.
3. Ensure you do not have any containers or images related to the labs in docker.
3. Open one of the labs in VSCode.
4. When prompted to reopen in a container, select yes.

Result:
During the container initialization process, an error is thrown in the remote extension host log that CodeTour cannot be loaded. The unauthenticated codetour is not launched, but the codetour does eventually load and can be started via the CodeTour panel.

Expected: 
Having codetour installed should have no effect on containerized labs.

Remediation:
For now, remove codetour from the locally installed VSCode.

**Comment by kazemicode** [comment]
@jesposito Does this issue persist today? Haven't seen this pop up locally and I have CodeTour installed locally.
